# Generated by Django 6.0.2 on 2026-02-23 17:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchadoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('CONFORME', 'Conforme'), ('CONFORME_RESSALVAS', 'Conforme com Ressalvas'), ('NAO_CONFORME', 'Não Conforme'), ('INDETERMINADO', 'Indeterminado')], max_length=20, verbose_name='Classificação')),
                ('descricao', models.TextField(verbose_name='Descrição do Achado')),
                ('normas_aplicaveis', models.TextField(blank=True, verbose_name='Normas Aplicáveis')),
                ('impacto_financeiro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Impacto Financeiro (R$)')),
                ('recomendacao', models.TextField(blank=True, verbose_name='Recomendação')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achados', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Achado de Auditoria',
                'verbose_name_plural': 'Achados de Auditoria',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='AnaliseCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo_ok', models.BooleanField(blank=True, null=True, verbose_name='Base de cálculo correta')),
                ('base_calculo_obs', models.TextField(blank=True, verbose_name='Observações - Base de Cálculo')),
                ('composicao_remuneracao_ok', models.BooleanField(blank=True, null=True, verbose_name='Composição da remuneração correta')),
                ('composicao_remuneracao_obs', models.TextField(blank=True, verbose_name='Observações - Composição da Remuneração')),
                ('media_integralidade_ok', models.BooleanField(blank=True, null=True, verbose_name='Média/integralidade correta')),
                ('media_integralidade_obs', models.TextField(blank=True, verbose_name='Observações - Média/Integralidade')),
                ('cotas_familiares_ok', models.BooleanField(blank=True, null=True, verbose_name='Cotas familiares corretas')),
                ('cotas_familiares_obs', models.TextField(blank=True, verbose_name='Observações - Cotas Familiares')),
                ('teto_acumulacao_ok', models.BooleanField(blank=True, null=True, verbose_name='Teto/acumulação verificado')),
                ('teto_acumulacao_obs', models.TextField(blank=True, verbose_name='Observações - Teto/Acumulação')),
                ('reajuste_ok', models.BooleanField(blank=True, null=True, verbose_name='Reajuste correto')),
                ('reajuste_obs', models.TextField(blank=True, verbose_name='Observações - Reajuste')),
                ('resultado', models.CharField(choices=[('CONFORME', 'Conforme'), ('RESSALVAS', 'Conforme com Ressalvas'), ('NAO_CONFORME', 'Não Conforme'), ('INDETERMINADO', 'Indeterminado')], default='INDETERMINADO', max_length=20, verbose_name='Resultado')),
                ('data_analise', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Análise')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisecalculo', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Análise de Cálculo',
                'verbose_name_plural': 'Análises de Cálculo',
            },
        ),
        migrations.CreateModel(
            name='AnaliseElegibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquadramento_correto', models.BooleanField(blank=True, null=True, verbose_name='Enquadramento correto')),
                ('enquadramento_obs', models.TextField(blank=True, verbose_name='Observações - Enquadramento')),
                ('requisitos_idade', models.BooleanField(blank=True, null=True, verbose_name='Requisitos de idade atendidos')),
                ('requisitos_idade_obs', models.TextField(blank=True, verbose_name='Observações - Requisitos de Idade')),
                ('tempo_contribuicao_ok', models.BooleanField(blank=True, null=True, verbose_name='Tempo de contribuição verificado')),
                ('tempo_contribuicao_obs', models.TextField(blank=True, verbose_name='Observações - Tempo de Contribuição')),
                ('tempo_servico_publico_ok', models.BooleanField(blank=True, null=True, verbose_name='Tempo de serviço público verificado')),
                ('tempo_servico_publico_obs', models.TextField(blank=True, verbose_name='Observações - Tempo de Serviço Público')),
                ('condicao_dependente_ok', models.BooleanField(blank=True, null=True, verbose_name='Condição de dependente verificada')),
                ('condicao_dependente_obs', models.TextField(blank=True, verbose_name='Observações - Condição de Dependente')),
                ('normas_vigentes_epoca_ok', models.BooleanField(blank=True, null=True, verbose_name='Normas vigentes à época aplicadas')),
                ('normas_vigentes_epoca_obs', models.TextField(blank=True, verbose_name='Observações - Normas Vigentes')),
                ('resultado', models.CharField(choices=[('CONFORME', 'Conforme'), ('RESSALVAS', 'Conforme com Ressalvas'), ('NAO_CONFORME', 'Não Conforme'), ('INDETERMINADO', 'Indeterminado')], default='INDETERMINADO', max_length=20, verbose_name='Resultado')),
                ('data_analise', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Análise')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analiseelegibilidade', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Análise de Elegibilidade',
                'verbose_name_plural': 'Análises de Elegibilidade',
            },
        ),
        migrations.CreateModel(
            name='ConferenciaFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_concedido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Concedido (R$)')),
                ('valor_pago_folha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago na Folha (R$)')),
                ('rubricas_ok', models.BooleanField(blank=True, null=True, verbose_name='Rubricas corretas')),
                ('rubricas_obs', models.TextField(blank=True, verbose_name='Observações - Rubricas')),
                ('reajuste_aplicado_ok', models.BooleanField(blank=True, null=True, verbose_name='Reajuste aplicado corretamente')),
                ('reajuste_aplicado_obs', models.TextField(blank=True, verbose_name='Observações - Reajuste Aplicado')),
                ('teto_constitucional_ok', models.BooleanField(blank=True, null=True, verbose_name='Teto constitucional observado')),
                ('teto_constitucional_obs', models.TextField(blank=True, verbose_name='Observações - Teto Constitucional')),
                ('tipo_divergencia', models.CharField(choices=[('SEM_DIVERGENCIA', 'Sem Divergência'), ('PAGAMENTO_MAIOR', 'Pagamento Maior que o Concedido'), ('PAGAMENTO_MENOR', 'Pagamento Menor que o Concedido')], default='SEM_DIVERGENCIA', max_length=20, verbose_name='Tipo de Divergência')),
                ('impacto_financeiro_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Impacto Financeiro Estimado (R$)')),
                ('resultado', models.CharField(choices=[('CONFORME', 'Conforme'), ('RESSALVAS', 'Conforme com Ressalvas'), ('NAO_CONFORME', 'Não Conforme'), ('INDETERMINADO', 'Indeterminado')], default='INDETERMINADO', max_length=20, verbose_name='Resultado')),
                ('data_analise', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Análise')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conferenciafolha', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Conferência de Folha',
                'verbose_name_plural': 'Conferências de Folha',
            },
        ),
    ]
