# Generated by Django 6.0.2 on 2026-02-23 21:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
        ('processos', '0003_processo_limitacao_tecnica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecalculo',
            name='redutor_obs',
            field=models.TextField(blank=True, verbose_name='Observações - Redutor'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='redutor_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Redutor aplicado corretamente'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='carreira_cargo_obs',
            field=models.TextField(blank=True, verbose_name='Observações - Carreira e Cargo'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='carreira_cargo_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Carreira e cargo verificados'),
        ),
        migrations.CreateModel(
            name='NotaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Nota Técnica')),
                ('limitacao_documental', models.TextField(blank=True, verbose_name='Limitações Documentais')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_tecnica', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Nota Técnica',
                'verbose_name_plural': 'Notas Técnicas',
            },
        ),
    ]
