# Generated by Django 5.1.5 on 2026-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_analisecalculo_redutor_obs_analisecalculo_redutor_ok_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecalculo',
            name='ano_base_reajuste',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano Base do Reajuste'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='valor_base_reajuste',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Base para Verificação de Reajuste (R$)'),
        ),
    ]
