# Generated by Django 5.1.5 on 2026-03-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0003_reajuste_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisecalculo',
            name='diferenca_folha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferença Apurada vs Folha (R$)'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='indice_inss_aplicado',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Índice INSS Aplicado (%)'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='lei_municipal_aplicada',
            field=models.CharField(blank=True, max_length=300, verbose_name='Lei Municipal Aplicada'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='metodo_reajuste_aplicado',
            field=models.CharField(blank=True, help_text='PARIDADE_MUNICIPAL ou INDICE_INSS', max_length=30, verbose_name='Método de Reajuste Aplicado'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='regime_compativel',
            field=models.BooleanField(blank=True, null=True, verbose_name='Regime de reajuste compatível com método aplicado'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='regime_compativel_obs',
            field=models.TextField(blank=True, verbose_name='Obs - Compatibilidade de Regime'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='valor_devido_mes_corrente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Devido no Mês Corrente (R$)'),
        ),
        migrations.AddField(
            model_name='analisecalculo',
            name='valor_reconstruido_ano',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Reconstruído (R$)'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='marco_temporal_obs',
            field=models.TextField(blank=True, verbose_name='Observações - Marco Temporal'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='marco_temporal_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Marco temporal de ingresso verificado'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='tempo_carreira_obs',
            field=models.TextField(blank=True, verbose_name='Observações - Tempo de Carreira'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='tempo_carreira_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tempo de carreira verificado'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='tempo_no_cargo_obs',
            field=models.TextField(blank=True, verbose_name='Observações - Tempo no Cargo'),
        ),
        migrations.AddField(
            model_name='analiseelegibilidade',
            name='tempo_no_cargo_ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tempo no cargo verificado'),
        ),
    ]
