# Generated by Django 5.1.5 on 2026-05-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0006_add_acumulacao_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenciafolha',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='conferenciafolha',
            name='valor_esperado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Esperado após Reajustes (R$)'),
        ),
        migrations.AlterField(
            model_name='analisecalculo',
            name='acumulacao_cargos_acumulaveis',
            field=models.BooleanField(blank=True, help_text='Verdadeiro se os cargos de origem são acumuláveis por força constitucional (professor+técnico-científico, dois médicos, etc.).', null=True, verbose_name='Cargos/benefícios acumuláveis (art. 37, XVI CF/88)?'),
        ),
        migrations.AlterField(
            model_name='analisecalculo',
            name='acumulacao_regular',
            field=models.BooleanField(blank=True, help_text='True = regular, False = irregular (vedada ou supera o teto).', null=True, verbose_name='Acumulação regular?'),
        ),
        migrations.AlterField(
            model_name='analisecalculo',
            name='acumulacao_valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Soma de todos os benefícios acumulados.', max_digits=12, null=True, verbose_name='Valor total acumulado (R$)'),
        ),
        migrations.AlterField(
            model_name='analisecalculo',
            name='houve_acumulacao',
            field=models.BooleanField(blank=True, help_text='Indica se o beneficiário acumula este benefício com outro (RPPS, RGPS ou cargo ativo).', null=True, verbose_name='Houve acumulação de benefícios?'),
        ),
    ]
