# Generated by Django 5.2.14 on 2026-06-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0007_add_valor_esperado_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenciafolha',
            name='tipo_divergencia',
            field=models.CharField(choices=[('SEM_DIVERGENCIA', 'Sem Divergência'), ('PAGAMENTO_MAIOR', 'Pagamento Maior que o Concedido'), ('PAGAMENTO_MENOR', 'Pagamento Menor que o Concedido'), ('COM_DIVERGENCIAS', 'Com Divergências (maior e menor)')], default='SEM_DIVERGENCIA', max_length=20, verbose_name='Tipo de Divergência'),
        ),
        migrations.CreateModel(
            name='DivergenciaFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRIENIO_MAIOR', 'Triênio calculado a maior'), ('REAJUSTE_MENOR', 'Reajuste aplicado a menor'), ('REAJUSTE_MAIOR', 'Reajuste aplicado a maior'), ('RUBRICA_INDEVIDA', 'Rubrica indevida'), ('OUTRO_MAIOR', 'Pagamento a maior (outro)'), ('OUTRO_MENOR', 'Pagamento a menor (outro)')], max_length=20, verbose_name='Tipo')),
                ('impacto', models.CharField(choices=[('MAIOR', 'Pagamento a maior'), ('MENOR', 'Pagamento a menor')], max_length=5, verbose_name='Impacto')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('base_legal', models.TextField(blank=True, verbose_name='Base Legal')),
                ('detectado_automaticamente', models.BooleanField(default=False)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergencias', to='analise.conferenciafolha', verbose_name='Conferência')),
            ],
            options={
                'verbose_name': 'Divergência de Folha',
                'verbose_name_plural': 'Divergências de Folha',
                'ordering': ['tipo'],
            },
        ),
    ]
