# Generated by Django 5.2.14 on 2026-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0008_add_divergencia_folha'),
    ]

    operations = [
        migrations.AddField(
            model_name='divergenciafolha',
            name='achado_gerado',
            field=models.BooleanField(default=False),
        ),
    ]
