# Generated by Django 6.0.2 on 2026-02-23 17:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='Matrícula')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('cargo', models.CharField(blank=True, max_length=200, verbose_name='Cargo/Função')),
                ('carreira', models.CharField(blank=True, max_length=200, verbose_name='Carreira')),
            ],
            options={
                'verbose_name': 'Beneficiário',
                'verbose_name_plural': 'Beneficiários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='Número do Lote')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='ABERTO', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Número do Processo')),
                ('tipo_beneficio', models.CharField(choices=[('APOS_VOLUNTARIA', 'Aposentadoria Voluntária'), ('APOS_INCAPACIDADE', 'Aposentadoria por Incapacidade'), ('APOS_COMPULSORIA', 'Aposentadoria Compulsória'), ('PENSAO_MORTE', 'Pensão por Morte'), ('REVISAO_REENQUADRAMENTO', 'Revisão/Reenquadramento')], max_length=30, verbose_name='Tipo de Benefício')),
                ('status_processo', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANALISE', 'Em Análise'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_concessao', models.DateField(blank=True, null=True, verbose_name='Data de Concessão')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='processos.beneficiario', verbose_name='Beneficiário')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.lote', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='DadosBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_calculo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Base de Cálculo (R$)')),
                ('valor_concedido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Concedido (R$)')),
                ('valor_pago_folha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago na Folha (R$)')),
                ('tempo_contribuicao', models.CharField(blank=True, max_length=50, verbose_name='Tempo de Contribuição')),
                ('tempo_servico_publico', models.CharField(blank=True, max_length=50, verbose_name='Tempo de Serviço Público')),
                ('idade_concessao', models.IntegerField(blank=True, null=True, verbose_name='Idade na Concessão')),
                ('regra_aplicada', models.CharField(blank=True, max_length=200, verbose_name='Regra Aplicada')),
                ('integralidade', models.BooleanField(blank=True, null=True, verbose_name='Integralidade')),
                ('proporcionalidade', models.CharField(blank=True, max_length=50, verbose_name='Proporcionalidade')),
                ('teto_constitucional_observado', models.BooleanField(blank=True, null=True, verbose_name='Teto Constitucional Observado')),
                ('criterio_reajuste', models.CharField(blank=True, max_length=200, verbose_name='Critério de Reajuste')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_beneficio', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Dados do Benefício',
                'verbose_name_plural': 'Dados dos Benefícios',
            },
        ),
    ]
