# Generated by Django 6.0.2 on 2026-02-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='instituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutos.instituto', verbose_name='Instituto RPPS'),
        ),
    ]
