# Generated by Django 6.0.2 on 2026-02-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0002_processo_instituto'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='limitacao_tecnica',
            field=models.TextField(blank=True, help_text='Registre aqui a ausência ou insuficiência de documentos essenciais (cf. cláusula 12.4)', verbose_name='Limitações Técnicas'),
        ),
    ]
