# Generated by Django 5.1.5 on 2026-03-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0003_processo_limitacao_tecnica'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReajusteINSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano')),
                ('vigencia', models.DateField(verbose_name='Vigência')),
                ('percentual_acima_minimo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Reajuste (acima do mínimo)')),
                ('percentual_piso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% Reajuste (benefícios no piso)')),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Mínimo (R$)')),
                ('teto_inss', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teto INSS (R$)')),
                ('base_legal', models.CharField(blank=True, max_length=200, verbose_name='Base Legal')),
            ],
            options={
                'verbose_name': 'Reajuste INSS',
                'verbose_name_plural': 'Reajustes INSS',
                'ordering': ['-ano'],
            },
        ),
    ]
