# Generated by Django 5.1.5 on 2026-03-16 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0004_reajuste_inss'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbeneficio',
            name='cargo_paradigma',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cargo Paradigma'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='classe_paradigma',
            field=models.CharField(blank=True, max_length=100, verbose_name='Classe do Cargo Paradigma'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='marco_temporal_ingresso',
            field=models.DateField(blank=True, null=True, verbose_name='Marco Temporal de Ingresso no Serviço Público'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='nivel_paradigma',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nível do Cargo Paradigma'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='referencia_paradigma',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referência do Cargo Paradigma'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='regime_reajuste',
            field=models.CharField(choices=[('PARIDADE', 'Paridade (vinculado ao cargo ativo)'), ('MEDIA', 'Média (índice INSS)'), ('NAO_DEFINIDO', 'Não Definido')], default='NAO_DEFINIDO', max_length=20, verbose_name='Regime de Reajuste'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='tempo_carreira',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tempo de Carreira'),
        ),
        migrations.AddField(
            model_name='dadosbeneficio',
            name='tempo_no_cargo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tempo no Cargo'),
        ),
        migrations.CreateModel(
            name='HistoricoReajusteBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_reajuste', models.IntegerField(verbose_name='Ano')),
                ('norma_reajuste', models.CharField(blank=True, max_length=300, verbose_name='Norma / Lei de Reajuste')),
                ('percentual_reajuste', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Percentual de Reajuste (%)')),
                ('valor_reconstruido_ano', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Reconstruído no Ano (R$)')),
                ('metodo_reajuste', models.CharField(choices=[('PARIDADE_MUNICIPAL', 'Paridade — Lei Municipal'), ('INDICE_INSS', 'Índice INSS (benefícios sem paridade)')], default='INDICE_INSS', max_length=30, verbose_name='Método de Reajuste')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Observação')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_reajuste', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Histórico de Reajuste do Benefício',
                'verbose_name_plural': 'Históricos de Reajuste dos Benefícios',
                'ordering': ['processo', 'ano_reajuste'],
                'unique_together': {('processo', 'ano_reajuste')},
            },
        ),
    ]
