# Generated by Django 5.1.5 on 2026-03-20 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0005_add_regime_reajuste_paradigma_historico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContrachequeAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(verbose_name='Mês de Referência do Contracheque')),
                ('valor_vencimento', models.DecimalField(blank=True, decimal_places=2, help_text='Para regime MÉDIA: informar apenas a parcela vencimento básico do contracheque do mês.', max_digits=12, null=True, verbose_name='Valor do Vencimento/Salário no Contracheque (R$)')),
                ('ultima_remuneracao_cargo', models.DecimalField(blank=True, decimal_places=2, help_text='Para regime PARIDADE: remuneração atual do servidor ativo no cargo equivalente.', max_digits=12, null=True, verbose_name='Última Remuneração do Cargo Efetivo Paradigma (R$)')),
                ('lei_reajuste_municipal', models.CharField(blank=True, help_text='Ex: Lei nº 1.234/2025 — reajuste de 5% a partir de 01/03/2025.', max_length=300, verbose_name='Lei Municipal de Reajuste (servidores em atividade)')),
                ('percentual_reajuste_lei', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Percentual de Reajuste da Lei Municipal (%)')),
                ('data_vigencia_reajuste', models.DateField(blank=True, null=True, verbose_name='Data de Vigência do Reajuste Municipal')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Registro')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contracheque', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Contracheque do Processo',
                'verbose_name_plural': 'Contracheques dos Processos',
            },
        ),
    ]
