# Generated by Django 5.1.5 on 2026-03-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0006_add_contracheque_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertidaoTempoContribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certidao', models.CharField(blank=True, max_length=100, verbose_name='Número da Certidão')),
                ('orgao_emissor', models.CharField(help_text='Ex: INSS, IPSM-MG, RJU Federal, RPPS Município de Barra Mansa', max_length=200, verbose_name='Órgão Emissor')),
                ('tipo_origem', models.CharField(choices=[('INSS_RGPS', 'RGPS/INSS'), ('RPPS_MUNICIPAL', 'RPPS Municipal (outro município)'), ('RPPS_ESTADUAL', 'RPPS Estadual'), ('RPPS_FEDERAL', 'RPPS Federal (RJU/União)')], max_length=20, verbose_name='Tipo de Origem')),
                ('data_inicio_periodo', models.DateField(blank=True, null=True, verbose_name='Início do Período')),
                ('data_fim_periodo', models.DateField(blank=True, null=True, verbose_name='Fim do Período')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão da Certidão')),
                ('cert_anos', models.PositiveIntegerField(default=0, verbose_name='Anos (certificado)')),
                ('cert_meses', models.PositiveIntegerField(default=0, verbose_name='Meses (certificado)')),
                ('cert_dias', models.PositiveIntegerField(default=0, verbose_name='Dias (certificado)')),
                ('possui_concomitancia', models.BooleanField(default=False, verbose_name='Possui período concomitante?')),
                ('conc_anos', models.PositiveIntegerField(default=0, verbose_name='Anos concomitantes')),
                ('conc_meses', models.PositiveIntegerField(default=0, verbose_name='Meses concomitantes')),
                ('conc_dias', models.PositiveIntegerField(default=0, verbose_name='Dias concomitantes')),
                ('descricao_concomitancia', models.TextField(blank=True, help_text='Descreva o período e o vínculo simultâneo com o RPPS atual que originou a concomitância.', verbose_name='Descrição da concomitância')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certidoes_tempo', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Certidão de Tempo de Contribuição',
                'verbose_name_plural': 'Certidões de Tempo de Contribuição',
                'ordering': ['processo', 'data_inicio_periodo'],
            },
        ),
    ]
