# Generated by Django 5.1.5 on 2026-03-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0007_add_certidao_tempo_contribuicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certidaotempocontribuicao',
            name='tipo_origem',
            field=models.CharField(choices=[('INSS_RGPS', 'RGPS/INSS'), ('INSS_MUNICIPIO', 'INSS Município (órgão público)'), ('RPPS_MUNICIPAL', 'RPPS Municipal (outro município)'), ('RPPS_ESTADUAL', 'RPPS Estadual'), ('RPPS_FEDERAL', 'RPPS Federal (RJU/União)')], max_length=20, verbose_name='Tipo de Origem'),
        ),
        migrations.CreateModel(
            name='ContribuicaoPrevidenciaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField(verbose_name='Competência (mês/ano)')),
                ('salario_contribuicao', models.DecimalField(decimal_places=2, help_text='Valor bruto do salário de contribuição na competência.', max_digits=12, verbose_name='Salário de Contribuição (R$)')),
                ('indice_correcao', models.DecimalField(blank=True, decimal_places=6, help_text='Fator de correção para atualizar o valor à data de concessão (ex: INPC acumulado).', max_digits=10, null=True, verbose_name='Índice de Correção Monetária')),
                ('valor_corrigido', models.DecimalField(blank=True, decimal_places=2, help_text='Salário de contribuição atualizado monetariamente. Calculado automaticamente se informado o índice.', max_digits=12, null=True, verbose_name='Valor Corrigido (R$)')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='Observações')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribuicoes', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Contribuição Previdenciária',
                'verbose_name_plural': 'Contribuições Previdenciárias',
                'ordering': ['processo', 'competencia'],
                'unique_together': {('processo', 'competencia')},
            },
        ),
    ]
