# Generated by Django 5.1.5 on 2026-03-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0008_add_contribuicao_previdenciaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbeneficio',
            name='media_contribuicoes',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Média das contribuições previdenciárias apurada para cálculo do benefício (regime MÉDIA).', max_digits=12, null=True, verbose_name='Média das Contribuições (R$)'),
        ),
    ]
