# Generated by Django 5.1.5 on 2026-03-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0009_add_media_contribuicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosbeneficio',
            name='proporcionalidade_percentual',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fração do benefício proporcional aplicada. Ex: 55.4155 para 6008/10950.', max_digits=7, null=True, verbose_name='Percentual de Proporcionalidade (%)'),
        ),
    ]
