# Generated by Django 5.1.5 on 2026-04-15 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0010_add_proporcionalidade_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='tipo_beneficio',
            field=models.CharField(choices=[('APOS_VOLUNTARIA', 'Aposentadoria Voluntária por Tempo de Contribuição (Integral)'), ('APOS_VOLUNTARIA_PROP', 'Aposentadoria Voluntária por Idade (Proventos Proporcionais)'), ('APOS_INCAPACIDADE', 'Aposentadoria por Incapacidade Permanente'), ('APOS_COMPULSORIA', 'Aposentadoria Compulsória'), ('PENSAO_MORTE', 'Pensão por Morte'), ('REVISAO_REENQUADRAMENTO', 'Revisão/Reenquadramento')], max_length=30, verbose_name='Tipo de Benefício'),
        ),
        migrations.CreateModel(
            name='DocumentoProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRACHEQUE_ATIVO', 'Contracheque Ativo'), ('CONTRACHEQUE_INATIVO', 'Contracheque Inativo'), ('OUTRO', 'Outro Documento')], max_length=30, verbose_name='Tipo de Documento')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Arquivo')),
                ('nome_original', models.CharField(blank=True, max_length=255, verbose_name='Nome Original')),
                ('data_upload', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Upload')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.processo', verbose_name='Processo')),
            ],
            options={
                'verbose_name': 'Documento do Processo',
                'verbose_name_plural': 'Documentos dos Processos',
                'ordering': ['processo', 'tipo'],
            },
        ),
    ]
