# Generated by Django 5.1.5 on 2026-04-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0011_alter_processo_tipo_beneficio_documentoprocesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='tipo_beneficio',
            field=models.CharField(choices=[('APOS_VOLUNTARIA', 'Aposentadoria Voluntária por Tempo de Contribuição (Integral)'), ('APOS_VOLUNTARIA_PROP', 'Aposentadoria Voluntária por Idade (Proventos Proporcionais)'), ('APOS_VOLUNTARIA_POR_IDADE', 'Aposentadoria Voluntária por Idade'), ('APOS_VOLUNTARIA_PROP_IDADE', 'Aposentadoria Voluntária por Idade com Proventos Proporcionais'), ('APOS_VOLUNTARIA_IDADE_TC', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição'), ('APOS_INCAPACIDADE', 'Aposentadoria por Incapacidade Permanente'), ('APOS_INVALIDEZ_PERMANENTE', 'Aposentadoria por Invalidez Permanente'), ('APOS_COMPULSORIA', 'Aposentadoria Compulsória'), ('APOS_ESPECIAL_MAGISTERIO', 'Aposentadoria Especial do Magistério'), ('PENSAO_MORTE', 'Pensão por Morte'), ('REVISAO_REENQUADRAMENTO', 'Revisão/Reenquadramento')], max_length=50, verbose_name='Tipo de Benefício'),
        ),
    ]
