# Generated by Django 5.1.5 on 2026-05-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0012_alter_processo_tipo_beneficio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrachequeauditoria',
            name='demonstrativo_json',
            field=models.TextField(blank=True, help_text='Importado automaticamente do PDF do holerite.', verbose_name='Demonstrativo de Pagamento (JSON)'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='tipo_beneficio',
            field=models.CharField(choices=[('APOS_VOLUNTARIA', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição (Integral)'), ('APOS_VOLUNTARIA_PROP', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição (Proporcional)'), ('APOS_VOLUNTARIA_POR_IDADE', 'Aposentadoria Voluntária por Idade'), ('APOS_VOLUNTARIA_PROP_IDADE', 'Aposentadoria Voluntária por Idade com Proventos Proporcionais'), ('APOS_VOLUNTARIA_IDADE_TC', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição'), ('APOS_INCAPACIDADE', 'Aposentadoria por Invalidez Permanente (Integral)'), ('APOS_INVALIDEZ_PERMANENTE', 'Aposentadoria por Invalidez Permanente (Proporcional)'), ('APOS_COMPULSORIA', 'Aposentadoria Compulsória'), ('APOS_ESPECIAL_MAGISTERIO', 'Aposentadoria Especial do Magistério'), ('PENSAO_MORTE', 'Pensão por Morte'), ('REVISAO_REENQUADRAMENTO', 'Revisão/Reenquadramento')], max_length=50, verbose_name='Tipo de Benefício'),
        ),
    ]
