# Generated by Django 5.1.5 on 2026-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0013_add_demonstrativo_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='reajusteinss',
            name='fatores_pro_rata',
            field=models.JSONField(blank=True, default=dict, help_text='Para benefícios concedidos no ano anterior ao reajuste. Chave: mês de concessão (1–12). Valor: percentual de reajuste. Ex: {"1": 3.90, "2": 3.90, "3": 2.38, ...}', verbose_name='Fatores Pro-Rata por Mês de Concessão'),
        ),
    ]
