# Generated by Django 5.2.14 on 2026-06-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0014_reajuste_inss_pro_rata'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrachequeauditoria',
            name='percentual_trienio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual total de triênio/anuênio acumulado. Aplicado sobre o vencimento base.', max_digits=6, null=True, verbose_name='Percentual do Triênio (%)'),
        ),
        migrations.AddField(
            model_name='contrachequeauditoria',
            name='vencimento_base_paradigma',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Parcela do vencimento básico do cargo paradigma, sem adicionais. Base de cálculo do triênio.', max_digits=12, null=True, verbose_name='Vencimento Base do Cargo Paradigma (R$)'),
        ),
    ]
