# Generated by Django 6.0.2 on 2026-02-23 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('lei_organica', models.CharField(blank=True, max_length=200, verbose_name='Lei Orgânica')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Instituto RPPS',
                'verbose_name_plural': 'Institutos RPPS',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraAposentadoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficio', models.CharField(choices=[('APOS_VOLUNTARIA', 'Aposentadoria Voluntária'), ('APOS_INCAPACIDADE', 'Aposentadoria por Incapacidade'), ('APOS_COMPULSORIA', 'Aposentadoria Compulsória'), ('PENSAO_MORTE', 'Pensão por Morte'), ('REVISAO_REENQUADRAMENTO', 'Revisão/Reenquadramento')], max_length=30, verbose_name='Tipo de Benefício')),
                ('norma_base', models.CharField(max_length=300, verbose_name='Norma Base')),
                ('vigente_desde', models.DateField(verbose_name='Vigente Desde')),
                ('vigente_ate', models.DateField(blank=True, null=True, verbose_name='Vigente Até')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('idade_minima_homem', models.IntegerField(blank=True, null=True, verbose_name='Idade Mínima (Homem)')),
                ('idade_minima_mulher', models.IntegerField(blank=True, null=True, verbose_name='Idade Mínima (Mulher)')),
                ('tempo_contribuicao_homem', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Contribuição - Homem (anos)')),
                ('tempo_contribuicao_mulher', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Contribuição - Mulher (anos)')),
                ('tempo_servico_publico', models.IntegerField(blank=True, null=True, verbose_name='Tempo de Serviço Público (anos)')),
                ('tempo_no_cargo', models.IntegerField(blank=True, null=True, verbose_name='Tempo no Cargo (anos)')),
                ('integralidade', models.BooleanField(blank=True, null=True, verbose_name='Integralidade')),
                ('proporcionalidade_formula', models.CharField(blank=True, max_length=200, verbose_name='Fórmula de Proporcionalidade')),
                ('teto_remuneratorio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Teto Remuneratório (R$)')),
                ('criterio_reajuste', models.CharField(blank=True, max_length=50, verbose_name='Critério de Reajuste')),
                ('cota_inicial_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cota Inicial (%)')),
                ('cota_por_dependente_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Cota por Dependente (%)')),
                ('reversibilidade', models.BooleanField(blank=True, null=True, verbose_name='Reversibilidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='institutos.instituto', verbose_name='Instituto')),
            ],
            options={
                'verbose_name': 'Regra de Aposentadoria',
                'verbose_name_plural': 'Regras de Aposentadoria',
                'ordering': ['tipo_beneficio', '-vigente_desde'],
            },
        ),
    ]
