# Generated by Django 5.1.5 on 2026-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='aderiu_ec103_2019',
            field=models.BooleanField(default=False, help_text='Marque se o município promulgou lei própria de reforma previdenciária com base na EC 103/2019, revogando as regras constitucionais anteriores.', verbose_name='Aderiu à Reforma da EC 103/2019'),
        ),
        migrations.AddField(
            model_name='regraaposentadoria',
            name='norma_federal',
            field=models.BooleanField(default=False, help_text='Regras oriundas da CF/88, EC 41/2003, EC 47/2005, EC 70/2012 — exibidas em todos os institutos que não aderiram à EC 103/2019.', verbose_name='Norma Federal/Constitucional'),
        ),
    ]
