# Generated by Django 5.1.5 on 2026-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0002_add_norma_federal_aderiu_ec103'),
    ]

    operations = [
        migrations.AddField(
            model_name='regraaposentadoria',
            name='tempo_carreira',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo de Carreira (anos)'),
        ),
    ]
