# Generated by Django 5.1.5 on 2026-05-15 19:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0004_add_subsidio_prefeito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regraaposentadoria',
            name='tipo_beneficio',
            field=models.CharField(choices=[('APOS_VOLUNTARIA', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição (Integral)'), ('APOS_VOLUNTARIA_PROP', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição (Proporcional)'), ('APOS_VOLUNTARIA_POR_IDADE', 'Aposentadoria Voluntária por Idade'), ('APOS_VOLUNTARIA_PROP_IDADE', 'Aposentadoria Voluntária por Idade com Proventos Proporcionais'), ('APOS_VOLUNTARIA_IDADE_TC', 'Aposentadoria Voluntária por Idade e Tempo de Contribuição'), ('APOS_INCAPACIDADE', 'Aposentadoria por Invalidez Permanente (Integral)'), ('APOS_INVALIDEZ_PERMANENTE', 'Aposentadoria por Invalidez Permanente (Proporcional)'), ('APOS_COMPULSORIA', 'Aposentadoria Compulsória'), ('APOS_ESPECIAL_MAGISTERIO', 'Aposentadoria Especial do Magistério'), ('PENSAO_MORTE', 'Pensão por Morte'), ('REVISAO_REENQUADRAMENTO', 'Revisão/Reenquadramento')], max_length=30, verbose_name='Tipo de Benefício'),
        ),
        migrations.CreateModel(
            name='LeiMunicipalReajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ex: 1.582/2025', max_length=50, verbose_name='Número da Lei')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Ementa')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('data_vigencia', models.DateField(verbose_name='Data de Vigência (efeitos financeiros)')),
                ('percentual', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Percentual de Reajuste (%)')),
                ('base_indice', models.CharField(blank=True, help_text='Ex: IPCA 2024, IPC-A, INPC', max_length=100, verbose_name='Índice de Referência')),
                ('base_legal', models.TextField(blank=True, verbose_name='Fundamento Legal')),
                ('aplica_inativos', models.BooleanField(default=True, verbose_name='Aplica-se a proventos de inatividade')),
                ('aplica_pensoes', models.BooleanField(default=True, verbose_name='Aplica-se a pensões')),
                ('arquivo', models.FileField(blank=True, upload_to='leis_municipais/', verbose_name='Arquivo PDF')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('instituto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leis_reajuste', to='institutos.instituto', verbose_name='Instituto')),
            ],
            options={
                'verbose_name': 'Lei Municipal de Reajuste',
                'verbose_name_plural': 'Leis Municipais de Reajuste',
                'ordering': ['data_vigencia'],
                'unique_together': {('instituto', 'numero')},
            },
        ),
    ]
