# Generated by Django 5.2.14 on 2026-06-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0005_add_lei_municipal_reajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='norma_trienio',
            field=models.CharField(blank=True, help_text='Ex: Art. 71 da Lei nº 05/1991', max_length=300, verbose_name='Base Legal do Triênio'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='trienio_demais_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual de cada triênio a partir do 2º. Calculado sobre o vencimento base.', max_digits=5, null=True, verbose_name='Demais Triênios (%)'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='trienio_limite_periodos',
            field=models.IntegerField(blank=True, help_text='Número máximo de triênios passíveis de acumulação.', null=True, verbose_name='Limite de Triênios'),
        ),
        migrations.AddField(
            model_name='instituto',
            name='trienio_primeiro_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentual do primeiro triênio. Calculado sobre o vencimento base.', max_digits=5, null=True, verbose_name='1º Triênio (%)'),
        ),
    ]
