# Generated by Django 5.2.14 on 2026-06-05 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0006_add_trienio_instituto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAuditora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('sigla', models.CharField(blank=True, max_length=20, verbose_name='Sigla')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Empresa Auditora',
                'verbose_name_plural': 'Empresas Auditoras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='instituto',
            name='empresa_auditora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutos', to='institutos.empresaauditora', verbose_name='Empresa Auditora'),
        ),
    ]
