# Generated by Django 5.2.14 on 2026-06-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0007_add_empresa_auditora'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaauditora',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo'),
        ),
    ]
