# Generated by Django 6.0.6 on 2026-06-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutos', '0008_add_logo_empresa_auditora'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institutos/logos/', verbose_name='Logo'),
        ),
    ]
